/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: '欢迎',
    },
    {
      type: 'category',
      label: '产品相关',
      items: ['product/notification-system'],
    },
    {
      type: 'category',
      label: '技术相关',
      items: ['tech/docusaurus-github', 'tech/docusaurus-content', 'tech/docusaurus-comment', 'tech/docusaurus-embed'],
    },
  ],

};

module.exports = sidebars;
